#!/usr/bin/env python3
"""One-off styling pass: map legacy Tailwind palette tokens to theme-backed classes."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src"

REPLACEMENTS: list[tuple[str, str]] = [
    (r"\bbg-slate-950/50\b", "bg-surface-50/50"),
    (r"\bbg-slate-950\b", "bg-surface-default"),
    (r"\bbg-slate-900/60\b", "bg-surface-50/60"),
    (r"\bbg-slate-900/40\b", "bg-surface-50/40"),
    (r"\bbg-slate-900/80\b", "bg-surface-50/80"),
    (r"\bbg-slate-900/70\b", "bg-surface-50/70"),
    (r"\bbg-slate-900\b", "bg-surface-default"),
    (r"\bbg-slate-800/80\b", "bg-surface-100/80"),
    (r"\bbg-slate-800/50\b", "bg-surface-100/50"),
    (r"\bbg-slate-800/40\b", "bg-surface-100/40"),
    (r"\bbg-slate-800\b", "bg-surface-100"),
    (r"\bbg-slate-750\b", "bg-surface-200"),
    (r"\bbg-slate-700/50\b", "bg-surface-200/50"),
    (r"\bbg-slate-700/40\b", "bg-surface-200/40"),
    (r"\bbg-slate-700/30\b", "bg-surface-200/30"),
    (r"\bbg-slate-700/20\b", "bg-surface-200/20"),
    (r"\bbg-slate-700\b", "bg-surface-200"),
    (r"\bbg-slate-600\b", "bg-surface-300"),
    (r"\bborder-slate-900\b", "border-border"),
    (r"\bborder-slate-800\b", "border-border"),
    (r"\bborder-slate-700\b", "border-border"),
    (r"\bborder-slate-600\b", "border-border"),
    (r"\bborder-slate-500\b", "border-border"),
    (r"\bdivide-slate-800\b", "divide-border"),
    (r"\bdivide-slate-700\b", "divide-border"),
    (r"\btext-slate-950\b", "text-theme-text-primary"),
    (r"\btext-slate-100\b", "text-theme-text-primary"),
    (r"\btext-slate-200\b", "text-theme-text-primary"),
    (r"\btext-slate-300\b", "text-theme-text-secondary"),
    (r"\btext-slate-400\b", "text-theme-text-secondary"),
    (r"\btext-slate-500\b", "text-theme-text-muted"),
    (r"\btext-slate-600\b", "text-theme-text-muted"),
    (r"\btext-slate-700\b", "text-theme-text-muted"),
    (r"\bplaceholder-slate-500\b", "placeholder:text-theme-text-muted"),
    (r"\bplaceholder-slate-400\b", "placeholder:text-theme-text-muted"),
    (r"\bring-slate-600\b", "ring-border"),
    (r"\bfocus:ring-indigo-500\b", "focus:ring-accent/50"),
    (r"\bfocus:ring-indigo-400\b", "focus:ring-accent/45"),
    (r"\bcaret-indigo-400\b", "caret-accent"),
    (r"\btext-indigo-400\b", "text-accent"),
    (r"\btext-indigo-300\b", "text-accent-hover"),
    (r"\bbg-indigo-900/30\b", "bg-accent/15"),
    (r"\bbg-indigo-600\b", "bg-accent/80"),
    (r"\bhover:bg-indigo-600\b", "hover:bg-accent/50"),
    (r"\bhover:bg-indigo-500\b", "hover:bg-accent/40"),
    (r"\bactive:bg-indigo-500\b", "active:bg-accent/35"),
    (r"\bactive:bg-indigo-400\b", "active:bg-accent/30"),
    (r"\bfrom-slate-900\b", "from-surface-default"),
    (r"\bto-slate-900\b", "to-surface-default"),
    (r"\bvia-slate-900\b", "via-surface-default"),
    (r"\bvia-slate-800\b", "via-surface-100"),
    (r"\bvia-\[#09162f\]", "via-[var(--color-bg-mid)]"),
    (r"\bbg-white/5\b", "bg-[var(--bg-glass-subtle)]"),
    (r"\bbg-white/10\b", "bg-[var(--bg-glass)]"),
    (r"\bhover:bg-white/5\b", "hover:bg-[var(--bg-hover)]"),
    (r"\bhover:bg-white/10\b", "hover:bg-[var(--bg-hover)]"),
    (r"\bborder-white/10\b", "border-border"),
    (r"\bborder-white/5\b", "border-[var(--color-border)]"),
    (r"\baccent-indigo-500\b", "accent"),
    (r"\baccent-emerald-500\b", "accent"),
    (r"\bborder-indigo-400\b", "border-accent"),
    (r"\btext-emerald-600\b", "text-profit"),
    (r"\btext-emerald-500\b", "text-profit"),
    (r"\btext-emerald-400\b", "text-profit"),
    (r"\btext-emerald-300\b", "text-profit"),
    (r"\btext-red-400\b", "text-loss"),
    (r"\btext-red-500\b", "text-risk-high"),
    (r"\btext-amber-500\b", "text-risk-medium"),
    (r"\btext-amber-400\b", "text-risk-medium"),
    (r"\btext-amber-300\b", "text-risk-medium"),
    (r"\btext-sky-400\b", "text-accent-hover"),
    (r"\btext-fuchsia-400\b", "text-accent-glow"),
    (r"\btext-fuchsia-300\b", "text-accent-hover"),
    (r"\btext-purple-400\b", "text-accent-glow"),
    (r"\btext-purple-300\b", "text-accent-hover"),
    (r"\btext-violet-300\b", "text-accent-hover"),
    (r"\btext-violet-400\b", "text-accent-glow"),
    (r"\bhover:bg-slate-500\b", "hover:bg-surface-400"),
    (r"\bhover:border-slate-400\b", "hover:border-border-bright"),
    (r"\bbg-emerald-900/25\b", "bg-profit/15"),
    (r"\bbg-emerald-900/20\b", "bg-profit/12"),
    (r"\bbg-emerald-700\b", "bg-profit"),
    (r"\bbg-emerald-600\b", "bg-profit/95"),
    (r"\bhover:bg-emerald-600\b", "hover:bg-profit"),
    (r"\bhover:bg-emerald-500\b", "hover:bg-profit/90"),
    (r"\bhover:bg-emerald-700\b", "hover:bg-profit"),
    (r"\bbg-sky-700\b", "bg-accent/80"),
    (r"\bhover:bg-sky-600\b", "hover:bg-accent/70"),
    (r"\bbg-amber-900/50\b", "bg-risk-medium/20"),
    (r"\bbg-amber-900/40\b", "bg-risk-medium/18"),
    (r"\bbg-amber-900/30\b", "bg-risk-medium/15"),
    (r"\bbg-amber-900/25\b", "bg-risk-medium/12"),
    (r"\bborder-amber-800\b", "border-risk-medium/50"),
    (r"\bborder-amber-700\b", "border-risk-medium/45"),
    (r"\bborder-amber-500\b", "border-risk-medium/40"),
    (r"\bhover:bg-amber-800\b", "hover:bg-risk-medium/25"),
    (r"\bhover:bg-amber-600\b", "hover:bg-risk-medium"),
    (r"\bhover:bg-amber-500\b", "hover:bg-risk-medium/90"),
    (r"\bbg-amber-700\b", "bg-risk-medium"),
    (r"\bbg-amber-600\b", "bg-risk-medium/95"),
    (r"\bbg-sky-500/20\b", "bg-accent/15"),
    (r"\btext-sky-300\b", "text-accent"),
    (r"\bborder-sky-500/30\b", "border-accent/30"),
    (r"\bbg-emerald-500/20\b", "bg-profit/15"),
    (r"\bborder-emerald-500/30\b", "border-profit/30"),
    (r"\bbg-violet-500/20\b", "bg-accent/12"),
    (r"\bborder-violet-500/30\b", "border-accent/30"),
    (r"\bbg-fuchsia-500/20\b", "bg-accent-glow/12"),
    (r"\bborder-fuchsia-500/30\b", "border-accent-glow/25"),
    (r"\bbg-purple-500/20\b", "bg-accent-glow/12"),
    (r"\bborder-purple-500/30\b", "border-accent-glow/25"),
    (r"\bbg-amber-500/20\b", "bg-risk-medium/15"),
    (r"\bborder-amber-500/30\b", "border-risk-medium/30"),
    (r"\bbg-lime-900/35\b", "bg-profit/12"),
    (r"\boutline-lime-400\b", "outline-profit/60"),
    (r"\boutline-amber-400\b", "outline-risk-medium/60"),
    (r"\bfocus:ring-amber-500\b", "focus:ring-risk-medium/50"),
    (r"\bborder-amber-500\b", "border-risk-medium/40"),
    (r"\bbg-indigo-900/20\b", "bg-accent/12"),
]

import re


def main() -> None:
    for path in sorted(ROOT.rglob("*.tsx")):
        text = path.read_text(encoding="utf-8")
        orig = text
        for pat, repl in REPLACEMENTS:
            text = re.sub(pat, repl, text)
        if text != orig:
            path.write_text(text, encoding="utf-8")
            print("updated", path.relative_to(ROOT.parent))


if __name__ == "__main__":
    main()
